<footer id="site-footer" class="site-footer">
  <div class="site-container">
    <div class="logo"><a href="#"><img src="theme/images/logo-min.png" alt=""/></a></div>
    <div class="menu">
      <ul>
        <li><a href="#">About</a></li>
        <li><a href="#">Careers</a></li>
        <li><a href="#">Media</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </div>
    <p>5749 NW 132nd St, Oklahoma City, OK 73142   (405) 603-1200</p>
  </div>
</footer>