<header id="site-header" class="site-header">
  <div class="header-top">
    <div class="menu">
      <ul>
        <li><a href="#">Water Management</a></li>
        <li class="active"><a href="#">Crescent Services</a></li>
        <li><a href="#">Ameriflow</a></li>
        <li><a href="#">SJB</a></li>
      </ul>
    </div>
  </div>
  <div class="header-bottom">
    <div class="site-container">
      <div class="logo"><a href="#"><img src="theme/images/logo.png" alt=""/></a></div>
      <div class="login-btn">
        <a class="btn" href="#">EnviroEdge</a>
      </div>
      <div class="hamburger-wrapper">
        <a href="#" class="hamburger"></a>
      </div>
      <nav class="nav">
        <ul class="menu">
          <li class="active expanded">
            <a href="#">Services </a>

            <ul class="menu">
              <li class="expanded"><a href="#">Water services</a>
                <ul class="menu">
                  <li><a href="#"> Test</a></li>
                  <li><a href="#"> Test</a></li>

                </ul>
              </li>
              <li><a href="#">Environmental services</a> </li>
            </ul>

          </li>
          <li><a href="#">Rentals</a></li>
          <li><a href="#">Enviro-Edge</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </nav>
    </div>
  </div>
</header>